language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install pytest pytest-cov pytest-pep8 coveralls"
script: "make clean test"
after_success: "coveralls"
branches:
  only:
    - master
